# Benchmark Problem 3A

In [2]:
import material_pb2 as mat
import numpy as np

Define energy groups and normalized fission spectrum $\chi$,

In [6]:
energy_groups = [2e7, 1.353e6, 9.119e3, 3.928, 0.6251, 0.1457, 0.0569, 0]
sum = 0
chi_s = [0.59252, 0.40714, 3.3193e-4, 0, 0, 0, 0]
for chi in chi_s:
    sum += chi
normalized_chi = [chi/sum for chi in chi_s]

Base location to save material files:

In [5]:
folder = "/home/josh/repos/bart/benchmarks/kaist_benchmark_3A/"

In [7]:
def make_material(name, sigma_t, sigma_s, is_fissionable, nu_sig_f, 
                  chi):
    material = mat.Material()
    material.full_name = name
    material.id = name
    material.abbreviation = name
    material.is_fissionable = is_fissionable
    material.number_of_groups = 7

    eg = mat.Material.VectorProperty()
    eg.id = mat.Material.ENERGY_GROUPS
    eg.value.extend(energy_groups)

    material_sigma_t = mat.Material.VectorProperty()
    material_sigma_t.id = mat.Material.SIGMA_T
    material_sigma_t.value.extend(sigma_t)

    diff = mat.Material.VectorProperty()
    diff.id = mat.Material.DIFFUSION_COEFF
    diff.value.extend([1.0/(3.0 * val) for val in sigma_t])

    if is_fissionable:
        nsf = mat.Material.VectorProperty()
        nsf.id = mat.Material.NU_SIG_F
        nsf.value.extend(nu_sig_f)

        chi = mat.Material.VectorProperty()
        chi.id = mat.Material.CHI
        chi.value.extend(normalized_chi)

    material_sigma_s = mat.Material.MatrixProperty()
    material_sigma_s.id = mat.Material.SIGMA_S
    material_sigma_s.value.extend(sigma_s)

    material.vector_property.extend([eg, material_sigma_t, nsf, chi, diff])
    material.matrix_property.extend([material_sigma_s])

    filename = filename + name
    f = open(filename, 'wb')
    f.write(material.SerializeToString())
    f.close()

------------
## Materials

### (k) Reflector

In [8]:
sigma_t = [7.58384e-2, 2.4872e-1, 4.2163e-1, 
           5.3183e-1, 9.0849e-1, 1.3205, 2.3163]
sigma_s = [8.2716e-2, 0, 0, 0, 0, 0, 0,
           8.1963e-2, 4.7143e-1, 0, 0, 0, 0, 0,
           5.1642e-4, 9.9730e-2, 9.5552e-1, 0, 0, 0, 0,
           0, 0, 1.1014e-1, 7.0714-1, 2.3861e-3, 0, 0,
           0, 0, 1.5751e-2, 3.5409e-1, 8.9203e-1, 2.1673e-1, 9.8237e-2,
           0, 0, 2.8683e-3, 4.9958e-2, 4.2845e-1, 1.1936, 6.4545e-1,
           0, 0, 1.7862e-3, 2.2326e-2, 1.3581e-1, 4.3269e-1, 2.0233]

In [7]:
print(mox_43)

full_name: "KAIST MOX 4.3"
abbreviation: "c567_uo2"
id: "KAIST MOX 4.3"
number_of_groups: 7
is_fissionable: true
vector_property {
  id: ENERGY_GROUPS
  value: 1000000.0
  value: 1000.0
  value: 100.0
  value: 10.0
  value: 0.625
  value: 0.3125
  value: 0.15625
  value: 0.0
}
vector_property {
  id: SIGMA_T
  value: 0.21245
  value: 0.35547
  value: 0.48554
  value: 0.5594
  value: 0.31803
  value: 0.40146
  value: 0.57061
}
vector_property {
  id: NU_SIG_F
  value: 0.0020059984286999997
  value: 0.00202730297343
  value: 0.015705991756
  value: 0.04518301024
  value: 0.043342083919999996
  value: 0.20209009624000002
  value: 0.5257105352
}
vector_property {
  id: CHI
  value: 0.5879046044408233
  value: 0.41175622106198806
  value: 0.0003390568882681117
  value: 1.1760892063119394e-07
  value: 0.0
  value: 0.0
  value: 0.0
}
vector_property {
  id: DIFFUSION_COEFF
  value: 1.5689966266572528
  value: 0.9377256402321807
  value: 0.6865208496382035
  value: 0.5958765343820761
  value: 

In [11]:
uo_2 = mat.Material()
uo_2.full_name = "C5G7 UO_2"
uo_2.id = "c5g7_uo2"
uo_2.abbreviation = "c567_uo2"
uo_2.is_fissionable = True
uo_2.number_of_groups = 7

e_max = 1e6
energy_groups = [e_max, 1e3, 1e2, 1e1, 0.625, 0.625/2, 0.625/4, 0]
eg = mat.Material.VectorProperty()
eg.id = mat.Material.ENERGY_GROUPS
eg.value.extend(energy_groups)

sigma_t = mat.Material.VectorProperty()
sigma_t.id = mat.Material.SIGMA_T
sigma_t.value.extend([0.21245, 0.35547, 0.48554, 0.5594, 0.318030, 0.40146, 0.57061])

diff = mat.Material.VectorProperty()
diff.id = mat.Material.DIFFUSION_COEFF
diff.value.extend([1.0/(3.0 * val) for val in [0.21245, 0.35547, 0.48554, 0.5594, 0.318030, 0.40146, 0.57061]])

nsf = mat.Material.VectorProperty()
nsf.id = mat.Material.NU_SIG_F
nsf.value.extend([0.721206e-3 * 2.78145, 
                  8.19301e-4 * 2.47443, 
                  6.4532e-3 * 2.43383,
                 1.85648e-2 * 2.43380,
                 1.78084e-2 * 2.43380,
                 8.30348e-2 * 2.43380,
                 2.16004e-1 * 2.43380])

chi = mat.Material.VectorProperty()
chi.id = mat.Material.CHI
chi.value.extend([0.5879046044408233,
 0.41175622106198806,
 0.0003390568882681117,
 1.1760892063119394e-07,
 0.0,
 0.0,
 0.0])

sigma_s = mat.Material.MatrixProperty()
sigma_s.id = mat.Material.SIGMA_S
sigma_s.value.extend([1.27537e-1, 0, 0, 0, 0, 0, 0,
                      4.2378e-2, 3.24456e-1, 0, 0, 0, 0, 0,
                      9.4374e-6, 1.6314e-3, .45094, 0, 0, 0, 0,
                      5.5163e-9, 3.1427e-9, 2.6792e-3, .452565, 1.25250e-4, 0, 0,
                      0, 0, 0, 5.5664e-3, 2.71401e-1, 1.2968e-3, 0,
                      0, 0, 0, 0, 1.0255e-2, 2.65802e-1, 8.5458e-3, 
                      0, 0, 0, 0, 1.0021e-8, 1.6809e-2, 2.7308e-1])

uo_2.vector_property.extend([eg, sigma_t, nsf, chi, diff])
uo_2.matrix_property.extend([sigma_s])

filename = '/home/josh/repos/bart/benchmarks/c5g7/uo2.material'
f = open(filename, 'wb')
f.write(uo_2.SerializeToString())
f.close()

In [9]:
moderator = mat.Material()
moderator.full_name = "C5G7 moderator"
moderator.id = "c5g7_mod"
moderator.abbreviation = "c567_mod"
moderator.is_fissionable = False
moderator.number_of_groups = 7

e_max = 1e6
energy_groups = [e_max, 1e3, 1e2, 1e1, 0.625, 0.625/2, 0.625/4, 0]
eg = mat.Material.VectorProperty()
eg.id = mat.Material.ENERGY_GROUPS
eg.value.extend(energy_groups)

sigma_t = mat.Material.VectorProperty()
sigma_t.id = mat.Material.SIGMA_T
sigma_t.value.extend([0.23, 0.77646, 1.4842, 1.5052, 1.5592, 2.0254, 3.3057])

diff = mat.Material.VectorProperty()
diff.id = mat.Material.DIFFUSION_COEFF
diff.value.extend([1.0/(3.0 * val) for val in [0.23, 0.77646, 1.4842, 1.5052, 1.5592, 2.0254, 3.3057]])

sigma_s = mat.Material.MatrixProperty()
sigma_s.id = mat.Material.SIGMA_S
sigma_s.value.extend([4.44777e-2, 0, 0, 0, 0, 0, 0,
                      1.134e-1, 2.82334e-1, 0, 0, 0, 0, 0, 
                      7.2347e-4, 1.2994e-1, 3.45256e-1, 0, 0, 0, 0,
                      3.7499e-6, 6.234e-4, 2.2457e-1, 9.10284e-2, 7.1437e-5, 0, 0,
                      5.3184e-8, 4.8002e-5, 1.6999e-2, 4.1551e-1, 1.39138e-1, 2.2157e-3, 0,
                      0, 7.4486e-6, 2.6443e-3, 6.3732e-2, 5.1182e-1, 6.99913e-1, 1.3244e-1,
                      0, 1.0455e-6, 5.0344e-4, 1.2139e-2, 6.1229e-2, 5.3932e-1, 2.4807])
                      
    
moderator.vector_property.extend([eg, sigma_t, nsf, chi, diff])
moderator.matrix_property.extend([sigma_s])

filename = '/home/josh/repos/bart/benchmarks/c5g7/moderator.material'
f = open(filename, 'wb')
f.write(moderator.SerializeToString())
f.close()

In [10]:
print(moderator)

full_name: "C5G7 moderator"
abbreviation: "c567_mod"
id: "c5g7_mod"
number_of_groups: 7
vector_property {
  id: ENERGY_GROUPS
  value: 1000000.0
  value: 1000.0
  value: 100.0
  value: 10.0
  value: 0.625
  value: 0.3125
  value: 0.15625
  value: 0.0
}
vector_property {
  id: SIGMA_T
  value: 0.23
  value: 0.77646
  value: 1.4842
  value: 1.5052
  value: 1.5592
  value: 2.0254
  value: 3.3057
}
vector_property {
  id: NU_SIG_F
  value: 0.0020059984286999997
  value: 0.00202730297343
  value: 0.015705991756
  value: 0.04518301024
  value: 0.043342083919999996
  value: 0.20209009624000002
  value: 0.5257105352
}
vector_property {
  id: CHI
  value: 0.5879046044408233
  value: 0.41175622106198806
  value: 0.0003390568882681117
  value: 1.1760892063119394e-07
  value: 0.0
  value: 0.0
  value: 0.0
}
vector_property {
  id: DIFFUSION_COEFF
  value: 1.4492753623188404
  value: 0.4292987833672479
  value: 0.2245878812379284
  value: 0.22145451324297988
  value: 0.2137848469300496
  value: 0.1

In [1]:
import numpy as np

In [4]:
sigma_t = np.array([0.21245, 0.35547, 0.48554, 0.5594, 0.318030, 0.40146, 0.57061])
sigma_s = np.array([[1.27537e-1, 0, 0, 0, 0, 0, 0],
                      [4.2378e-2, 3.24456e-1, 0, 0, 0, 0, 0],
                      [9.4374e-6, 1.6314e-3, .45094, 0, 0, 0, 0],
                      [5.5163e-9, 3.1427e-9, 2.6792e-3, .452565, 1.25250e-4, 0, 0],
                      [0, 0, 0, 5.5664e-3, 2.71401e-1, 1.2968e-3, 0],
                      [0, 0, 0, 0, 1.0255e-2, 2.65802e-1, 8.5458e-3],
                      [0, 0, 0, 0, 1.0021e-8, 1.6809e-2, 2.7308e-1]])

array([[1.27537e-01, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [4.23780e-02, 3.24456e-01, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [9.43740e-06, 1.63140e-03, 4.50940e-01, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [5.51630e-09, 3.14270e-09, 2.67920e-03, 4.52565e-01, 1.25250e-04,
        0.00000e+00, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 5.56640e-03, 2.71401e-01,
        1.29680e-03, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.02550e-02,
        2.65802e-01, 8.54580e-03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00210e-08,
        1.68090e-02, 2.73080e-01]])

In [21]:
T = np.diag(sigma_t)
SL = np.tril(sigma_s, -1)
SU = np.triu(sigma_s, 1)
SD = np.diag(np.diag(sigma_s))
A = np.matmul(np.linalg.inv(T - SL - SD), SU)
eig_values, eig_vectors = np.linalg.eig(A)
idx = np.argmax(eig_values)
eigenfunction = eig_vectors[:,idx]
eigenfunction = eigenfunction/np.sum(eigenfunction)

In [22]:
print(eigenfunction
    )

[-0.         -0.         -0.          0.14480098  0.70575421  0.14145336
  0.00799145]


In [23]:
T

array([[0.21245, 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.     , 0.35547, 0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.48554, 0.     , 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     , 0.5594 , 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     , 0.     , 0.31803, 0.     , 0.     ],
       [0.     , 0.     , 0.     , 0.     , 0.     , 0.40146, 0.     ],
       [0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.57061]])

In [24]:
T - SL - SD

array([[ 8.49130e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         0.00000e+00,  0.00000e+00,  0.00000e+00],
       [-4.23780e-02,  3.10140e-02,  0.00000e+00,  0.00000e+00,
         0.00000e+00,  0.00000e+00,  0.00000e+00],
       [-9.43740e-06, -1.63140e-03,  3.46000e-02,  0.00000e+00,
         0.00000e+00,  0.00000e+00,  0.00000e+00],
       [-5.51630e-09, -3.14270e-09, -2.67920e-03,  1.06835e-01,
         0.00000e+00,  0.00000e+00,  0.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00, -5.56640e-03,
         4.66290e-02,  0.00000e+00,  0.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -1.02550e-02,  1.35658e-01,  0.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -1.00210e-08, -1.68090e-02,  2.97530e-01]])

In [25]:
np.linalg.inv(T - SL - SD)

array([[ 1.17767597e+01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 1.60919431e+01,  3.22435029e+01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 7.61951966e-01,  1.52029048e+00,  2.89017341e+01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 1.91092549e-02,  3.81266775e-02,  7.24795488e-01,
         9.36022839e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 2.28119317e-03,  4.55142374e-03,  8.65234426e-02,
         1.11738994e+00,  2.14458813e+01,  0.00000000e+00,
         0.00000000e+00],
       [ 1.72445679e-04,  3.44062646e-04,  6.54069723e-03,
         8.44685444e-02,  1.62119088e+00,  7.37147828e+00,
        -0.00000000e+00],
       [ 9.74242020e-06,  1.94380218e-05,  3.69520542e-04,
         4.77210016e-03,  9.15901337e-02,  4.16452722e-01,
         3.3610056

In [26]:
A

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.17236861e-03, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.39953089e-04, 2.78110189e-02, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.05796852e-05, 2.10236034e-03, 6.29951791e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.97705545e-07, 1.18774085e-04, 3.55892167e-03]])